# Generated by Django 5.0 on 2023-12-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
